blog/models.py
# coding=utf-8

import hmac

from markdown import Markdown
from flask import current_app
from flask_sqlalchemy import SQLAlchemy
from flask_redis import FlaskRedis
from sqlalchemy.dialects.mysql import LONGTEXT
from jieba.analyse import ChineseAnalyzer


db = SQLAlchemy()
redis = FlaskRedis()

md_converter = Markdown(
    output_format="html5",
    extensions=[
        "markdown.extensions.fenced_code",      # 代码块
        "markdown.extensions.codehilite",       # 代码块代码高亮
        "markdown.extensions.sane_lists",       # 非混合列表
        "markdown.extensions.smarty",           # 自动转译字符的 html 表示形式
        "markdown.extensions.tables",           # 表格
        "markdown.extensions.toc",              # 目录支持
        "markdown.extensions.meta",             # Meta-data 支持
    ],
    extension_configs={
        "markdown.extensions.codehilite": {"linenums": False},  # 不显示行号
    },
    strip=True,
)


class User(db.Model):
    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(64), unique=True, nullable=False)
    name = db.Column(db.String(64), default="")
    posts = db.relationship("Post", backref="author", lazy="dynamic")

    def __repr__(self):
        return "<User %r>" % self.email


class Category(db.Model):
    __tablename__ = "category"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128), unique=True, nullable=False)
    permalink = db.Column(db.String(128), nullable=False, unique=True)
    posts = db.relationship("Post", backref="category", lazy="dynamic")

    def __repr__(self):
        return "<Category %r>" % self.name

    def __init__(self, **kw):
        super(Category, self).__init__(**kw)
        if self.name is not None and self.permalink is None:
            self.permalink = hmac.new(
                current_app.config["HMAC_KEY"].encode("utf-8"),
                self.name.encode("utf-8"),
                "md5",
            ).hexdigest()


class Label(db.Model):
    __tablename__ = "label"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(128), unique=True, nullable=False)
    permalink = db.Column(db.String(128), nullable=False, unique=True)
    posts = db.relationship(
        "Post",
        secondary="post_label_ref",
        backref=db.backref("labels", lazy="dynamic"),
        lazy="dynamic",
    )

    def __repr__(self):
        return "<Label %r>" % self.name

    def __init__(self, **kw):
        super(Label, self).__init__(**kw)
        if self.name is not None and self.permalink is None:
            self.permalink = hmac.new(
                current_app.config["HMAC_KEY"].encode("utf-8"),
                self.name.encode("utf-8"),
                "md5",
            ).hexdigest()


class Post(db.Model):
    __tablename__ = "post"
    __searchable__ = ["title", "content"]
    __analyzer__ = ChineseAnalyzer()

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(128), nullable=False)
    content = db.Column(LONGTEXT, nullable=False)
    html_content = db.Column(LONGTEXT, nullable=False, default="")
    create_at = db.Column(db.DateTime, nullable=False)
    update_at = db.Column(db.DateTime, nullable=False)
    path = db.Column(db.String(256), nullable=False, unique=True)
    permalink = db.Column(db.String(128), nullable=False, unique=True)
    status = db.Column(db.Integer, nullable=False, default=1)   # 1:公开，2:删除
    author_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey(Category.id), nullable=False)

    def __repr__(self):
        return "<Post %r>" % self.title

    def __init__(self, **kw):
        super(Post, self).__init__(**kw)
        if self.path is not None and self.permalink is None:
            self.permalink = hmac.new(
                current_app.config["HMAC_KEY"].encode("utf-8"),
                self.path.encode("utf-8"),
                "md5",
            ).hexdigest()


class PostLabelRef(db.Model):
    __tablename__ = "post_label_ref"
    post_id = db.Column(db.Integer, db.ForeignKey(Post.id), primary_key=True)
    label_id = db.Column(db.Integer, db.ForeignKey(Label.id), primary_key=True)


@db.event.listens_for(Post.content, "set")
def on_changed_md(target, value, oldvalue, initiator):
    """转换 markdown 为 html"""
    target.html_content = md_converter.convert(value)

blog/__init__.py
# coding=utf-8

from flask import Flask
import flask_whooshalchemyplus
import jieba

from blog import views
from blog.models import db, redis
from blog.tasks import rq


def create_app(config_obj):
    """factory function"""
    app = Flask(__name__)
    app.config.from_object(config_obj)

    db.init_app(app)
    flask_whooshalchemyplus.init_app(app)
    redis.init_app(app)
    rq.init_app(app)

    views.init_app(app)

    jieba.initialize()

    return app

blog/libs/__init__.py
# coding=utf-8

from .dingtalk import DingTalkRobot
from .repo import PostRepo, WebhookSignature


__all__ = ["DingTalkRobot", "PostRepo", "WebhookSignature"]

blog/main/__init__.py
# coding=utf-8

from flask import Blueprint

bp_main = Blueprint("main", __name__)

from blog.main import views, errors

blog/tasks/__init__.py
# coding=utf-8

from flask_rq2 import RQ

rq = RQ()

blog/views/__init__.py
# coding=utf-8

from .main import bp_main
from .manage import bp_manage
from .webhook import bp_webhook
from .error import bp_error


def init_app(app):
    app.register_blueprint(bp_main)
    app.register_blueprint(bp_manage)
    app.register_blueprint(bp_webhook)
    app.register_blueprint(bp_error)

blog/views/common.py
# coding=utf-8

import functools

from flask import request, g, abort

__all__ = ["check_args"]

_allowed_types = ("int", "str", "bool", "list", "tuple", "dict", "set")


# 参数检查装饰器，传参格式 "arg_name:[?]arg_type"，?代表可选参数
def check_args(*expacted_args):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kw):
            g.args = {}
            request_args = _obtain_args()
            for arg in expacted_args:
                # 解析传参
                optional = True if "?" in arg else False
                arg_name, arg_type = arg.replace("?", "").split(":")
                # 检查 arg_type
                if arg_type not in _allowed_types:
                    raise ValueError("arg_type only support {types}.".format(
                        types=", ".join(_allowed_types),
                    ))
                # 如果 arg_value 存在且类型正确，存入 g.args 中，否则 correct=False
                arg_value = request_args.get(arg_name)
                if arg_value is not None:
                    try:
                        arg_value = eval(arg_type)(arg_value)
                        g.args[arg_name] = arg_value
                        correct = True
                    except (ValueError, TypeError):
                        correct = False
                else:
                    correct = False
                # 如果不是可选参数并且参数检查失败，抛出 HTTP 400 错误
                if not optional and not correct:
                    g.bad_request_tip = arg_name
                    abort(400)
            return func(*args, **kw)
        return wrapper
    return decorator


def _obtain_args():
    """
    获取请求参数，参数重复时只取一个。

    GET请求：获取 URL 参数。
    POST请求：参数优先级：JSON参数 > FORM参数 > URL参数。
    """
    if request.method == "GET":
        args = _obtain_get_args()
    elif request.method in ("POST", "PUT"):
        args = {}
        args.update(_obtain_get_args())
        args.update(_obtain_form_args())
        args.update(_obtain_json_args())
    else:
        args = {}
    return args


def _obtain_get_args():
    return request.args.to_dict(flat=True) or {}


def _obtain_json_args():
    return request.get_json(silent=True) or {}


def _obtain_form_args():
    return request.form.to_dict(flat=True) or {}

blog/views/error.py
# coding=utf-8

import traceback

from flask import Blueprint, render_template, g, request

from blog.tasks.notify import send_500_notify

bp_error = Blueprint("error", __name__)


@bp_error.app_errorhandler(400)
def http_400(e):
    if getattr(g, "bad_request_tip", None):
        tip = f"嗷嗷，请求参数 \"{g.bad_request_tip}\" 好像不太对呢 (・-・*)"  # noqa
    else:
        tip = "嗷嗷，BAD REQUEST，请检查请求参数 (・-・*)"
    return render_template("error.html", code=400, tip=tip), 400


@bp_error.app_errorhandler(403)
def http_403(e):
    tip = "抱歉，你没有权限访问这个页面 ╮(╯_╰)╭"
    return render_template("error.html", code=403, tip=tip), 403


@bp_error.app_errorhandler(404)
def http_404(e):
    tip = "诶，你来到了没有知识存在的荒原 (๑•́ ₃ •̀๑)"
    return render_template("error.html", code=404, tip=tip), 404


@bp_error.app_errorhandler(500)
def http_500(e):
    tip = "哎呀，服务器提出了一个问题 ಠ_ಠ"
    send_500_notify.queue(
        request.path,
        traceback.format_exception_only(type(e), e)[-1],
    )
    return render_template("error.html", code=500, tip=tip), 500

blog/views/main.py
# coding=utf-8

from flask import Blueprint, render_template, g, abort, send_from_directory, \
    current_app
from sqlalchemy import func

from blog.models import redis, md_converter, \
    Post, Category, Label, PostLabelRef
from .common import check_args

bp_main = Blueprint("main", __name__)


@bp_main.context_processor
def inject_contexts():
    """向模版中插入 categories、labels 和 statistic 变量"""
    results = Category.query \
        .join(Post) \
        .add_columns(func.count(Post.id)) \
        .filter(Post.status == 1) \
        .group_by(Category.id) \
        .order_by(func.count(Post.id).desc()) \
        .all()
    categories = [
        {"permalink": category.permalink, "name": category.name, "posts_count": count}
        for (category, count) in results if count != 0
    ]

    results = Label.query \
        .join(PostLabelRef) \
        .join(Post) \
        .add_columns(func.count(Post.id)) \
        .filter(Post.status == 1) \
        .group_by(Label.id) \
        .order_by(func.count(Post.id).desc()) \
        .all()
    labels = [
        {"permalink": label.permalink, "name": label.name, "posts_count": count}
        for (label, count) in results if count != 0
    ]

    statistic = {
        "last_update_at": redis.get("last_update_at"),
        "posts": Post.query.filter_by(status=1).count(),
        "categories": Category.query.count(),
        "labels": Label.query.count(),
    }

    return dict(
        categories=categories,
        labels=labels,
        statistic=statistic,
    )


@bp_main.route("/")
@check_args("page:?int")
def index():
    """主页"""
    page = g.args.get("page", 1)    # 页码
    per_page = 10                   # 分页数量
    pagination = Post.query \
        .filter_by(status=1) \
        .order_by(Post.create_at.desc()) \
        .paginate(page, per_page, error_out=False)
    posts = pagination.items

    return render_template(
        "index.html",
        posts=posts,
        pagination=pagination,
        endpoint="main.index",
    )


@bp_main.route("/p/<string:permalink>")
def post(permalink):
    """文章内容页"""
    post = Post.query.filter_by(status=1, permalink=permalink).one_or_none()
    if not post:
        abort(404)

    return render_template(
        "post.html",
        post=post,
    )


@bp_main.route("/categories")
@check_args("page:?int")
def categories():
    """所有分类页面"""
    page = g.args.get("page", 1)    # 页码
    per_page = 10                   # 分页数量
    pagination = Post.query \
        .filter_by(status=1) \
        .order_by(Post.create_at.desc()) \
        .paginate(page, per_page, error_out=False)
    posts = pagination.items

    return render_template(
        "categories.html",
        posts=posts,
        pagination=pagination,
        endpoint="main.categories",
    )


@bp_main.route("/category/<string:permalink>")
@check_args("page:?int")
def category(permalink):
    """分类详情页"""
    page = g.args.get("page", 1)    # 页码
    per_page = 10                   # 分页数量
    category = Category.query.filter_by(permalink=permalink).one_or_none()
    if not category:
        abort(404)

    pagination = category.posts \
        .filter_by(status=1) \
        .order_by(Post.create_at.desc()) \
        .paginate(page, per_page, error_out=False)
    posts = pagination.items

    return render_template(
        "category.html",
        category=category,
        pagination=pagination,
        posts=posts,
        endpoint="main.category",
    )


@bp_main.route("/labels")
def labels():
    """所有标签页面"""
    return render_template("labels.html")


@bp_main.route("/label/<string:permalink>")
@check_args("page:?int")
def label(permalink):
    """标签详情页"""
    page = g.args.get("page", 1)    # 页码
    per_page = 10                   # 分页数量
    label = Label.query.filter_by(permalink=permalink).one_or_none()
    if not label:
        abort(404)

    pagination = label.posts \
        .filter_by(status=1) \
        .order_by(Post.create_at.desc()) \
        .paginate(page, per_page, error_out=False)
    posts = pagination.items

    return render_template(
        "label.html",
        label=label,
        pagination=pagination,
        posts=posts,
        endpoint="main.label",
    )


@bp_main.route("/search")
@check_args("q:?str", "page:?int")
def search():
    """全文搜索文章标题和内容"""
    keyword = g.args.get("q", "").strip()
    page = g.args.get("page", 1)
    per_page = 10
    pagination = Post.query \
        .whoosh_search(keyword) \
        .filter_by(status=1) \
        .paginate(page, per_page, error_out=False)

    posts = pagination.items
    return render_template(
        "search.html",
        keyword=keyword,
        posts=posts,
        pagination=pagination,
        endpoint="main.search",
    )


@bp_main.route("/about")
def about():
    with open("README.md") as f:
        content = f.read()
    html_content = md_converter.convert(content)
    return render_template(
        "about.html",
        html_content=html_content,
    )


@bp_main.route("/robots.txt")
def robots_txt():
    return send_from_directory(current_app.static_folder, 'robots.txt')

blog/views/manage.py
# coding=utf-8

from flask import Blueprint

bp_manage = Blueprint("manage", __name__)


@bp_manage.route("/manage")
def manage():
    return "haha"

blog/views/webhook.py
# coding=utf-8

from flask import Blueprint, jsonify, request, current_app, g, abort

from blog.libs import WebhookSignature
from blog.tasks.update import update_posts
from .common import check_args

bp_webhook = Blueprint("webhook", __name__, url_prefix="/webhook")


@bp_webhook.errorhandler(400)
def http_400(e):
    errmsg = "invalid argument"
    if getattr(g, "bad_request_tip", None):
        errmsg += f" '{g.bad_request_tip}'"     # noqa
    return jsonify(dict(success=False, errmsg=errmsg)), 400


@bp_webhook.errorhandler(403)
def http_403(e):
    return jsonify(dict(success=False, errmsg="签名验证失败")), 403


@bp_webhook.errorhandler(404)
def http_404(e):
    return jsonify(dict(success=False, errmsg="404 NOT FOUND")), 404


@bp_webhook.route("/coding", methods=["POST"])
@check_args("ref:str?", "before:str?", "after:str?")
def coding_webhook():
    # 鉴权
    is_ok = WebhookSignature.calc_coding_signature(
        current_app.config["WEBHOOK_TOKEN"],
        request.data,
        request.headers.get("X-Coding-Signature", ""),
    )
    if not is_ok:
        abort(403)

    event = request.headers.get("X-Coding-Event", "ping")

    # 响应 push 事件
    if event == "push":
        diff_info = {
            "ref": g.args.get("ref"),
            "before": g.args.get("before"),
            "after": g.args.get("after"),
        }
        update_posts.queue(diff_info)
    # 响应 ping 事件
    elif event == "ping":
        pass

    return jsonify(dict(success=True))


@bp_webhook.route("/github", methods=["POST"])
@check_args("ref:str?", "before:str?", "after:str?")
def github_webhook():
    # 鉴权
    is_ok = WebhookSignature.calc_github_signature(
        current_app.config["WEBHOOK_TOKEN"],
        request.data,
        request.headers.get("X-Hub-Signature", ""),
    )
    if not is_ok:
        abort(403)

    event = request.headers.get("X-GitHub-Event", "ping")

    # 响应 push 事件
    if event == "push":
        diff_info = {
            "ref": g.args.get("ref"),
            "before": g.args.get("before"),
            "after": g.args.get("after"),
        }
        update_posts.queue(diff_info)
    # 响应 ping 事件
    elif event == "ping":
        pass

    return jsonify(dict(success=True))

blog/webhook/views.py
# coding=utf-8

from flask import jsonify, request, current_app

from blog.webhook import bp_webhook
from blog.libs.coding import CodingSignature


@bp_webhook.route("/coding", methods=["GET", "POST"])
def coding_webhook():
    # 鉴权
    is_ok = CodingSignature.check_webhook_signature(
        current_app.config["WEBHOOK_TOKEN"],
        request.data,
        request.headers.get("X-Coding-Signature", ""),
    )
    if not is_ok:
        return jsonify(dict(success=False, errmsg="签名验证失败")), 403

    event = request.headers.get("X-Coding-Event", "ping")
    # 响应 ping 事件
    if event == "ping":
        return jsonify(dict(success=True))
    # 获取更新列表
    data = request.json
    paths = {}
    for commit in data["commits"][::-1]:
        for type_ in ("added", "modified", "removed"):
            paths.update({file: type_ for file in commit[type_]})
    removed_paths = [i for i in paths if paths[i] == "removed"]
    updated_paths = [i for i in paths if paths[i] in ("added", "modified")]

    # Celery任务执行

    return jsonify(dict(success=True))

blog/templates/_macros.html
{# 这里定义可以重复使用的宏组件，包括分页导航、面包屑导航、文章列表等。 #}


{% macro pagination_widget(pagination, endpoint) %}
{% if pagination and pagination.pages > 1 %}
<nav aria-label="page navigation">
    <ul class="pagination justify-content-center">

{% if pagination.has_prev %}
        <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}">上一页</a></li>
{% endif %}

{% for p in pagination.iter_pages(1, 2, 3, 1) %}
    {% if p %}
        {% if p == pagination.page %}
        <li class="page-item active">
            <span class="page-link">{{ p }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
        </li>
        {% endif %}
    {% else %}
        <li class="page-item disabled"><span class="page-link">...</span></li>
    {% endif %}
{% endfor %}

{% if pagination.has_next %}
        <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}">下一页</a></li>
{% endif %}

    </ul>
</nav>
{% endif %}
{% endmacro %}


{% macro breadcrumb_widget(items) %}
{% if items %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        {% for nav_url, nav_text in items[:-1] %}
        <li class="breadcrumb-item"><a href="{{ nav_url }}">{{ nav_text }}</a></li>
        {% endfor %}
        <li class="breadcrumb-item active">{{ items[-1] }}</li>
    </ol>
</nav>
{% endif %}
{% endmacro %}


{% macro post_stream_widget(posts) %}
<div class="stream-list">

{% for post in posts %}
    <div class="stream-item">
        <h1 class="title"><a href="{{ url_for('main.post', permalink=post.permalink) }}">{{ post.title }}</a></h1>
        <ul class="list-inline info">
            <li class="list-inline-item">
                <a href="#">
                    <img src="{{ url_for('static', filename='img/avatar.png') }}" class="avatar">
                    {{ post.author.name }}
                </a>
            </li>
            <li class="list-inline-item">
                <span class="momentjs" data-time="{{ post.create_at.strftime('%Y-%m-%d %H:%M:%S') }}"></span>
            </li>
            <li class="list-inline-item">
                发布于
                <a href="{{ url_for('main.category', permalink=post.category.permalink) }}">{{ post.category.name }}</a>
            </li>
        </ul>
        <p class="summary">{{ post.html_content|striptags|truncate(200) }}</p>
    </div>
{% endfor %}

</div>
{% endmacro%}


{% macro category_card_widget(categories) %}
<div class="card mt20 sidebar-card">
    <div class="card-header">
        <i class="icon-folder-open"></i>
        分类
    </div>
    <ul class="list-group list-group-flush">
        {% for category in categories %}
        <a href="{{ url_for('main.category', permalink=category['permalink']) }}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            {{ category['name'] }}
            <span class="badge badge-pill badge-success">
                {{ category['posts_count'] }}
            </span>
        </a>
        {% endfor %}
    </ul>
</div>
{% endmacro %}


{% macro label_card_widget(labels, limit=None) %}
<div class="card mt20 sidebar-card">
    <div class="card-header">
        <i class="icon-tags"></i>
        标签{% if limit %}（Top {{ limit }}）{% endif %}
    </div>
    <div class="card-body list-inline">
        {% if limit %}{% set labels=labels[:limit] %}{% endif %}
        {% for label in labels %}
        <a href="{{ url_for('main.label', permalink=label['permalink']) }}" class="list-inline-item label-item">
            {{ label['name'] }}
            <span class="badge badge-light">{{ label['posts_count'] }}</span>
        </a>
        {% endfor %}
    </div>
</div>
{% endmacro %}

blog/templates/about.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% set active_menu = "main.about" %}

{% block title %}关于{% endblock %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='css/pygment.css') }}" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="post">
    <div id="post-content">
        {{ html_content|safe }}
    </div>
</div>

{% endblock %}

{% block sidebar %}
<div id="toc" class="d-none d-lg-block">
    <div class="title">目录</div>
    <div style="max-height: calc(100vh - 120px); overflow: hidden; overflow-y: auto;">
        <nav class="nav flex-column" id="post-toc"></nav>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $(document).ready(function() {
        var headers = $('#post-content').find('h1, h2, h3');
        var post_toc = $('#post-toc');
        var header_level = 'h1';
        // 生成目录
        for (var header of headers) {
            var new_a = $('<a class="nav-link"></a>');
            new_a.addClass('toc-' + header.localName);
            new_a.attr('href', '#' + header.getAttribute('id'));
            new_a.text(header.innerText);
            post_toc.append(new_a);
        };
        // 绑定滚动监听
        $('body').scrollspy({ target: '#post-toc' });
    });

    var toc_position = $('#toc').offset().top;
    var toc_width = $('#toc').width();

    // 滚动事件，修改目录部分的 position
    $(window).scroll(function() {
        var toc = $('#toc');
        if ($(window).scrollTop() >= toc_position-12){
            toc.css('width', toc_width);
            toc.css('top', 0);
            toc.css('position', 'fixed');
        } else {
            toc.css('width', '');
            toc.css('top', '');
            toc.css('position', '');
        };
    });
</script>
{% endblock %}

blog/templates/categories.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% set active_menu = "main.categories" %}
{% set breadcrumb_items = (
        (url_for("main.index"), "首页"),
        "所有分类",
    )
%}

{% block title %}所有分类{% endblock %}

{% block main %}
{{ macros.breadcrumb_widget(breadcrumb_items) }}
{{ macros.post_stream_widget(posts) }}
{{ macros.pagination_widget(pagination, endpoint) }}
{% endblock %}

{% block sidebar %}
{{ macros.category_card_widget(categories) }}
{% endblock %}

blog/templates/category.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% set active_menu = "main.categories" %}
{% set breadcrumb_items = (
        (url_for("main.index"), "首页"),
        (url_for("main.categories"), "所有分类"),
        category.name,
    )
%}

{% block title %}分类：{{ category.name }}{% endblock %}

{% block main %}
{{ macros.breadcrumb_widget(breadcrumb_items) }}
{{ macros.post_stream_widget(posts) }}
{{ macros.pagination_widget(pagination, endpoint, permalink=category.permalink) }}
{% endblock %}

{% block sidebar %}
{{ macros.category_card_widget(categories) }}
{% endblock %}

blog/templates/error.html
{% extends "base.html" %}

{% block title %}HTTP {{ code }}{% endblock %}

{% block styles %}
<link href="{{ url_for('static', filename='css/error.css') }}" rel="stylesheet">
{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}
<div id="box">
    <div>
        <h1>HTTP {{ code }}</h1>
        <p>{{ tip }}</p>
        <hr>
        <p class="text-center">
            <a href="{{ url_for('main.index') }}" class="btn btn-success">返回首页</a>
        </p>
    </div>
</div>
{% endblock %}

{% block footer %}
<div id="footer" class="text-center">© MrChi</div>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% set active_menu = "main.index" %}
{% set breadcrumb_items = (
        (url_for("main.index"), "首页"),
        "所有文章（按创建时间降序）",
    )
%}

{% block title %}首页{% endblock %}

{% block main %}
{{ macros.breadcrumb_widget(breadcrumb_items) }}
{{ macros.post_stream_widget(posts) }}
{{ macros.pagination_widget(pagination, endpoint) }}
{% endblock %}

{% block sidebar %}
<div class="card mt20 sidebar-card">
    <div class="card-header">Quote</div>
    <div class="card-body">
        <i class="icon-quote-left"></i>
        愿中国青年都摆脱冷气，只是向上走，不必听自暴自弃者流的话。能做事的做事，能发声的发声。有一分热，发一分光，就令萤火一般，也可以在黑暗里发一点光，不必等候炬火。此后如竟没有炬火：我便是唯一的光。
        <i class="icon-quote-right"></i>
        <br/>
        <span class="blockquote-footer text-right">鲁迅</span>
    </div>
</div>
{{ macros.category_card_widget(categories) }}
{{ macros.label_card_widget(labels, limit=20) }}
<div class="card mt20 mb20 sidebar-card">
    <div class="card-header">关于</div>
    <div class="card-body">
        <p><strong>MrChi</strong><br/>Python开发者，爱好广泛。</p>
        <p><a href="https://github.com/chiqj/" target="_blank" noopener>
            <i class="icon-github-alt icon-large"></i>
            GitHub
        </a></p>
        <span>Try again, fail again, fail better.</span>
    </div>
</div>
{% endblock %}

blog/templates/label.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% set active_menu = "main.labels" %}
{% set breadcrumb_items = (
        (url_for("main.index"), "首页"),
        (url_for("main.labels"), "所有标签"),
        label.name,
    )
%}

{% block title %}标签：{{ label.name }}{% endblock %}

{% block main %}
{{ macros.breadcrumb_widget(breadcrumb_items) }}
{{ macros.post_stream_widget(posts) }}
{{ macros.pagination_widget(pagination, endpoint, permalink=label.permalink) }}
{% endblock %}

{% block sidebar %}
{{ macros.label_card_widget(labels, limit=50) }}
{% endblock %}

blog/templates/labels.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% set active_menu = "main.labels" %}
{% set breadcrumb_items = (
        (url_for("main.index"), "首页"),
        "所有标签",
    )
%}

{% set badge_styles=(
        'badge-light',
    )
%}

{% block title %}所有标签{% endblock %}

{% block content %}
<div class="col-12">
    {{ macros.breadcrumb_widget(breadcrumb_items) }}
    <div class="card-body list-inline">
        {% if limit %}{% set labels=labels[:limit] %}{% endif %}
        {% for label in labels %}
        <a href="{{ url_for('main.label', permalink=label['permalink']) }}" class="label-item list-inline-item">
            {{ label['name'] }}
            <span class="badge badge-light">{{ label['posts_count'] }}</span>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block sidebar %}
{% endblock %}